### ISSUE TITLE
Kotlin dependency

### ISSUE THREAD

**Issue by hc-codersatlas** [Vonage/vonage-java-sdk#261]
The new 5.0.0 release has dependencies on Kotlin. Why is this required for a Java library?

**Comment by cr0wst** [comment]
This is a transitive dependency that comes from the JWT library which replaced the Auth0 library we were using.

Something I did notice, which I will be addressing with v5.1.0 is that the JWT library is also causing us to bring in some other unintended transitive dependencies like Mockito.

Here's a little more detailed information if you're curious how this might impact the size.

I did a bit of size comparison to see how much this affects the overall size of the distribution:

```
$ du -hs nexmo* | grep nexmo-java
9.0M	nexmo-java-4.4.0
9.7M	nexmo-java-5.0.0
5.9M	nexmo-java-5.1.0
```

It looks like going from 4.4.0 increased the size a bit, but most of that was because of the unintended test libraries being brought in. There's a significant drop when correctly switching Mockito to a test dependency because it also depends on Byte Buddy at a whopping 3.1 MB!

Here's a comparison of each dependency by size. Keep in mind that Auth0's JWT library is a shaded jar, so it contributes quite a bit to the overall size. I trimmed off anything less than 500K just for ease of readability.

```
$ ls -lhS nexmo-java-4.4.0/
total 18496
-rw-r--r--@ 1 crow  staff   4.7M Nov 14  2018 java-jwt-2.2.1.jar
-rw-r--r--@ 1 crow  staff   1.3M May 21 11:42 jackson-databind-2.9.9.jar
-rw-r--r--@ 1 crow  staff   754K May 21 11:43 httpclient-4.5.8.jar
```

Here's 5.0.0
```
$ ls -lhS nexmo-java-5.0.0/
total 19920
-rw-r--r--@ 1 crow  staff   3.1M Jun 17 15:56 byte-buddy-1.9.10.jar
-rw-r--r--@ 1 crow  staff   1.3M Jun 17 15:56 jackson-databind-2.9.9.jar
-rw-r--r--@ 1 crow  staff   1.2M Jun 17 15:56 kotlin-stdlib-1.3.31.jar
-rw-r--r--@ 1 crow  staff   754K Jun 17 15:56 httpclient-4.5.8.jar
-rw-r--r--@ 1 crow  staff   577K Jun 17 15:56 mockito-core-2.28.2.jar
```

And 5.1.0
```
$ ls -lhS nexmo-java-5.1.0/
total 12152
-rw-r--r--  1 crow  staff   1.3M Jun 17 15:56 jackson-databind-2.9.9.jar
-rw-r--r--  1 crow  staff   1.2M Jun 17 15:56 kotlin-stdlib-1.3.31.jar
-rw-r--r--  1 crow  staff   754K Jun 17 15:56 httpclient-4.5.8.jar
```

**Comment by hc-codersatlas** [comment]
Thanks for the evaluation but size isn't the only issue. Classes loaded, memory etc is too. Also frameworks like Spring scan the classpath and detects Kotlin. It will try to load auto configurations based on it etc. This didn't happen with 4.4 and below.

**Comment by SteveNewson** [comment]
I'd be inclined to agree with this. Looking at the code in the Nexmo JWT library, it amounts to five source files which could be trivially written in Java. You'd then eliminate the dependency on kotlin standard libraries altogether.

**Comment by yallen011** [comment]
The JWT library was originally in Java, but it relied on another package for the heavy lifting of generating JWTs and was a thin wrapper to do the things we needed. It used Auth0, and was a massive dependency.
The Kotlin rewrite was ultimately smaller and easier to maintain than the Auth0 one. So while the Kotlin standard library dependency is pulled in, it's actually still better off than the Auth0 dependency in straight Java.

Because of this, we decided that pulling in the Kotlin dependency is a better trade-off so we will not be making any changes in this regards at this time. I hope this gives a better explanation.

Thanks
